name: MrFirthy's Portfolio
title: Ashley Firth
description: The portfolio for Ashley Firth containing work, books, articles, talks, and a blog that chats mostly about management and productivity. I currently work at Octopus Energy, where I built and lead the Front-end Development department.
github: [metadata]
markdown: kramdown
assets:
  autoprefixer:
    browsers:
    - "last 2 versions"
    - "IE > 9"
plugins:
  - jekyll-paginate
paginate: 5
paginate_path: "/blog/page/:num/"
future: true