name: MrFirthy's Portfolio
title: MrFirthy's Portfolio
markdown: kramdown
assets:
  autoprefixer:
    browsers:
    - "last 2 versions"
    - "IE > 9"
plugins:
  - jekyll-paginate
paginate: 5
paginate_path: "/blog/page/:num/"