name: MrFirthy's Portfolio
title: Ashley Firth
description: Front-end Developer / Author / Manager / Speaker
github: [metadata]
markdown: kramdown
assets:
  autoprefixer:
    browsers:
    - "last 2 versions"
    - "IE > 9"
plugins:
  - jekyll-paginate
paginate: 5
paginate_path: "/blog/page/:num/"